lowercaseOutputName: true

##
# Kafka Producer and Consumer metrics for prometheus
##
rules:
- pattern: "kafka.(.*)<type=(.*)-metrics, client-id=(.*)><>"
  name: kafka_$1_$2-metrics
  labels:
    client_id: "$3"
  help: "Kafka client JMX metric $1 $2-metrics"
  type: GAUGE
- pattern: "kafka.(.*)<type=(.*)-metrics, client-id=(.*), node-id=(.*)><>"
  name: kafka_$1_$2
  labels:
    client_id: "$3"
    node_id: "$4"
  help: "Kafka client JMX metric $1 $2"
  type: GAUGE
# kafka.producer:type=producer-topic-metrics,client-id=([-.w]+),topic=([-.w]+)
- pattern: "kafka.(.*)<type=(.*)-metrics, client-id=(.*), topic=(.*)><>"
  name: kafka_$1_$2
  labels:
    client_id: "$3"
    topic: "$4"
  help: "Kafka client JMX metric $1 $2"
  type: GAUGE
- pattern: "kafka.(.*)<type=(.*)-metrics, client-id=(.*), topic=(.*)><>"
  name: kafka_$1_$2
  labels:
    client_id: "$3"
    topic: "$4"
  help: "Kafka client JMX metric $1 $2"
  type: GAUGE
- pattern : java.lang<type=(.*)>
